### ISSUE TITLE
[버그] 테스트 사이트 로그인 오류

### ISSUE THREAD

**Issue by gaon12** [PressDo/PressDoWiki#3]
### 실행 환경
- 사용 엔진 버전:  v2107a (ffede52)
- 사용 OS 정보: Windows 11
- 사용 기기 정보: Whale Browser
- 사용 DBMS 정보: 모름
- 사용 PHP 정보: 8.0 이상?

### 버그/오류 정보
자세한 내용을 하단에 서술해주세요.
테스트 해 보려고 [테스트 사이트](https://pressdo.prws.kr)로 가서 회원가입 한 이후, 가입때 입력한 정보로 로그인을 하려고 하니 `[오류!] 사용자 이름 또는 패스워드가 올바르지 않습니다.` 이런 오류가 뜹니다.

**Comment by aaei924** [comment]
해결했습니다.
