### ISSUE TITLE
[버그] 모바일 환경에서 로그인시 회원 아이콘(?) 짤림

### ISSUE THREAD

**Issue by gaon12** [PressDo/PressDoWiki#4]
### 실행 환경
- 사용 엔진 버전: v2107a (ffede52)
- 사용 OS 정보: iOS 15.2.1
- 사용 기기 정보: 아이폰 13 Pro
- 사용 DBMS 정보:모름
- 사용 PHP 정보:8.0 이상

### 버그/오류 정보
자세한 내용을 하단에 서술해주세요.

모바일 환경에서 로그인 하면, 회원 아이콘이 짤려서 보입니다.
![image](https://user-images.githubusercontent.com/34927797/149866858-adc59d0f-eace-40a8-ab3c-13ebde19f6f8.png)
![image](https://user-images.githubusercontent.com/34927797/149866869-8ec4e2e9-e4f1-4f50-8301-f909a82d91d6.jpeg)

**Comment by gaon12** [comment]
추가로 PC버전에서 회원 아이콘을 클릭하면, 팝업창이 맨오른쪽에서 뜹니다. 원래 회원 아이콘 바로 밑에 떠야 되는거 아닌가요?
![오류2](https://user-images.githubusercontent.com/34927797/149885433-ddbecaee-07d1-4d06-9dce-49fdfe8e982d.png)

**Comment by aaei924** [comment]
모두 오류가 맞습니다. 다만 디자인 영역 작업의 우선순위가 낮은 상태이기 때문에 개선이 늦을 수 있는 점 양해 바랍니다.

**Comment by aaei924** [comment]
![image](https://user-images.githubusercontent.com/72678477/209479483-4f842a7e-fe93-4a2e-be33-5c2533dc8bbe.jpeg)

2022-12-26 현 시점에서 이미 해결된 것으로 확인됩니다.
