### ISSUE TITLE
위키 설치 관련

### ISSUE THREAD

**Issue by MacoriDev** [PressDo/PressDoWiki#8]
호스팅케이알 리눅스 웹호스팅에 이 위키 엔진을 설치하고 싶은데 어떻게 해야 되나요?
내장 프로그램은 cpanel, wordpress 등이 있습니다.

**Comment by aaei924** [comment]
아직 완성된 프로그램이 아니므로 설치 및 사용에 대해 지원해 드리지 않고 있습니다.

관심가져 주셔서 감사합니다.
